### ISSUE TITLE
hey i tried to run this program and i got a virus

### ISSUE THREAD

**Issue by CLyonsDev** [Zer0897/dm-toolkit#3]
~~please help~~

nvm **FIXED**

**Comment by intendednull** [comment]
Did you try turning it off and on again?

**Comment by CLyonsDev** [comment]
this is a test
![1517710517949](https://user-images.githubusercontent.com/7199982/66368761-6738b000-e94e-11e9-9dd0-53679634fdb9.png)

**Comment by CLyonsDev** [comment]
thats how i feel when i open ur program
